import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className="bg-gray-100 sm:m-2">
      <body
        className={clsx(
          inter.className,
          'sm:max-w-screen-sm sm:max-h-[calc(100vh-2rem)] sm:mx-auto sm:rounded-2xl sm:overflow-hidden sm:shadow-sm'
        )}
      >
        {children}
      </body>
    </html>
  )
}
