import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import clsx from 'clsx'
import Head from 'next/head'
import StyledComponentsRegistry from '@/lib/registry'
import { Toaster } from '@/components/ui/sonner'
import { Tabbar } from '@/components/Tabbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="ko" className="bg-gray-100">
      <Head>
        <title>Coupang</title>
      </Head>
      <body className={clsx(inter.className)}>
        <StyledComponentsRegistry>
          {children}

          <Tabbar />
        </StyledComponentsRegistry>
      </body>
      <Toaster />
    </html>
  )
}
